name: "body_reid"
max_batch_size: 64
input [ {
  name: "data"
  data_type: TYPE_FP32
  format: FORMAT_NCHW
  dims: [3, 384, 128]
} ]
output [ {
  name: "View_1"
  data_type: TYPE_FP32
  dims: [512, 1, 1]
} ]
instance_group [ {
  name: "body_reid"
  count: 1
  gpus: 0
  kind: KIND_GPU
} ]
default_model_filename: "model.onnx"
dynamic_batching {
  preferred_batch_size: [ 8, 16, 32, 64 ]
  max_queue_delay_microseconds: 25000
}
